//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorScheme
    {
        public ColorScheme()
        {
            this.AppInfoes = new HashSet<AppInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NormalColor { get; set; }
        public string NormalTextColor { get; set; }
        public string DarkColor { get; set; }
        public string DarkTextColor { get; set; }
        public string LightColor { get; set; }
        public string LightTextColor { get; set; }
    
        public virtual ICollection<AppInfo> AppInfoes { get; set; }
    }
}
