//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppInfo
    {
        public AppInfo()
        {
            this.AppAds = new HashSet<AppAd>();
            this.AppChannels = new HashSet<AppChannel>();
            this.AppTags = new HashSet<AppTag>();
            this.CharacterApps = new HashSet<CharacterApp>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ColorSchemeId { get; set; }
        public string NameOnStore { get; set; }
        public string LinkOnStore { get; set; }
        public string ShortDesc { get; set; }
        public string LongDesc { get; set; }
    
        public virtual ICollection<AppAd> AppAds { get; set; }
        public virtual ICollection<AppChannel> AppChannels { get; set; }
        public virtual AppImage AppImage { get; set; }
        public virtual ColorScheme ColorScheme { get; set; }
        public virtual ICollection<AppTag> AppTags { get; set; }
        public virtual ICollection<CharacterApp> CharacterApps { get; set; }
    }
}
