//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppImage
    {
        public int AppId { get; set; }
        public string Logo { get; set; }
        public string PromotionLarge { get; set; }
        public string PromotionSmall { get; set; }
    
        public virtual AppInfo AppInfo { get; set; }
    }
}
