//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public Channel()
        {
            this.AppChannels = new HashSet<AppChannel>();
        }
    
        public int Id { get; set; }
        public string ChannelId { get; set; }
        public string Token { get; set; }
        public string TypeData { get; set; }
    
        public virtual ICollection<AppChannel> AppChannels { get; set; }
    }
}
