//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public Character()
        {
            this.CharacterApps = new HashSet<CharacterApp>();
            this.CharacterTags = new HashSet<CharacterTag>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Nickname { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CharacterApp> CharacterApps { get; set; }
        public virtual ICollection<CharacterTag> CharacterTags { get; set; }
    }
}
